
import React from 'react'
import { render, screen } from '@testing-library/react'

const mockHasLocale = jest.fn()
const mockSetRequestLocale = jest.fn()
const mockNotFound = jest.fn()

jest.mock('@/constants/system', () => ({
  APP_NAME: 'Test App',
}))

const mockRouting = {
  locales: ['en', 'vi'],
}

jest.mock('@/i18n/routing', () => ({
  routing: mockRouting,
}))

jest.mock('next-intl', () => ({
  hasLocale: (...args: unknown[]) => mockHasLocale(...args),
  NextIntlClientProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="next-intl-provider">{children}</div>
  ),
}))

jest.mock('next-intl/server', () => ({
  setRequestLocale: (...args: unknown[]) => mockSetRequestLocale(...args),
}))

jest.mock('next/navigation', () => ({
  notFound: () => mockNotFound(),
}))

jest.mock('@/providers/auth-provider', () => ({
  AuthProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="auth-provider">{children}</div>
  ),
}))

jest.mock('@/providers/query-client-provider', () => ({
  __esModule: true,
  default: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="react-query-provider">{children}</div>
  ),
}))

jest.mock('@/share/ui/sonner', () => ({
  Toaster: () => <div data-testid="toaster" />,
}))


describe('LocaleLayout module', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('exports metadata with APP_NAME', async () => {
    const { metadata } = await import('../layout')

    expect(metadata.title).toEqual({
      template: '%s | ' + 'Test App',
      default: 'Test App',
    })
    expect(metadata.description).toBe('Generated by Test App')
  })

  it('generateStaticParams returns locales from routing', async () => {
    const { generateStaticParams } = await import('../layout')

    const params = generateStaticParams()
    expect(params).toEqual(mockRouting.locales.map((locale) => ({ locale })))
  })

  it('calls notFound when locale is invalid', async () => {
    mockHasLocale.mockReturnValue(false)
    const { default: LocaleLayout } = await import('../layout')

    await LocaleLayout({
      children: <div>Child</div>,
      // params is awaited inside, but awaiting a plain object just returns it
      params: { locale: 'fr' } as any,
    })

    expect(mockHasLocale).toHaveBeenCalledWith(mockRouting.locales, 'fr')
    expect(mockNotFound).toHaveBeenCalled()
  })

  it('sets locale and renders providers when locale is valid', async () => {
    mockHasLocale.mockReturnValue(true)
    const { default: LocaleLayout } = await import('../layout')

    const element = await LocaleLayout({
      children: <div>Child</div>,
      params: { locale: 'vi' } as any,
    })

    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {})
    render(element)
    consoleSpy.mockRestore()

    expect(mockHasLocale).toHaveBeenCalledWith(mockRouting.locales, 'vi')
    expect(mockSetRequestLocale).toHaveBeenCalledWith('vi')
    expect(mockNotFound).not.toHaveBeenCalled()

    expect(screen.getByTestId('next-intl-provider')).toBeInTheDocument()
    expect(screen.getByTestId('react-query-provider')).toBeInTheDocument()
    expect(screen.getByTestId('auth-provider')).toBeInTheDocument()
    expect(screen.getByTestId('toaster')).toBeInTheDocument()
    expect(screen.getByText('Child')).toBeInTheDocument()
  })
})

